layout_spectrum: 0.9751682
typography_spectrum: 0.8833992
color:
  saturation: 0.02270685
  lightness: 0.5700855
  brandStrength: 0.7587661
  rhythmicContrast: 0.8682624
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: A Painful Life
